services:  
  - type: web    
    name: tweetcanvas-service    
    env: node    
    buildCommand: npm install    
    startCommand: npm start    
    plan: free    
    envVars:      
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD        
        value: "true"    
    build:      
      packages:        
          - google-chrome-stable    
    disk:      
      sizeGB: 1      
      mountPath: /mnt/data