services:  
  - type: web    
    name: tweetcanvas-service    
    env: node    
    buildCommand: npm install    
    startCommand: npm start    
    plan: free    
    envVars:      
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: "true" # You can now remove this if not needed
    build:      
      packages:
          - libnss3
          - libatk-bridge2.0-0
          - libxcomposite1
          - libxdamage1
          - libxrandr2
          - libasound2
          - libpangocairo-1.0-0
          - libcups2
          - libdrm2
          - libgbm1
          - libxkbcommon0
    disk:      
      sizeGB: 1      
      mountPath: /mnt/data
